import {Knex} from 'knex';

// A função seed insere uma ou mais entradas na tabela definida. É executada quando o comando db-s for rodado no terminal
export async function seed(knex: Knex) {
  await knex('steps').insert([
    {
      textStep:'y=a*x+b',
      orderStep:1,
      idField:1
    },
    {
      textStep:'y=a*x+b',
      orderStep:2,
      replaceStep:true,
      idField:1
    },
    {
      textStep:'ax=a*x',
      orderStep:3,
      evaluateStep:true,
      notShowStep:true,
      idField:1
    },
    {
      textStep:'y=ax+b',
      orderStep:4,
      replaceStep:true,
      idField:1
    },
    {
      textStep:'y=ax+b',
      orderStep:5,
      evaluateStep:true,
      idField:1
    },
    {
      textStep:'y=a*x+b',
      orderStep:1,
      idField:2
    },
    {
      textStep:'a=(y-b)/x',
      orderStep:2,
      idField:2
    },
    {
      textStep:'a=(y-b)/x',
      orderStep:3,
      replaceStep:true,
      idField:2
    },
    {
      textStep:'yb=y-b',
      orderStep:4,
      evaluateStep:true,
      notShowStep:true,
      idField:2
    },
    {
      textStep:'a=yb/x',
      orderStep:5,
      replaceStep:true,
      idField:2
    },
    {
      textStep:'a=yb/x',
      orderStep:6,
      evaluateStep:true,
      idField:2
    },
    {
      textStep:'y=a*x+b',
      orderStep:1,
      idField:3
    },
    {
      textStep:'x=(y-b)/a',
      orderStep:2,
      idField:3
    },
    {
      textStep:'x=(y-b)/a',
      orderStep:3,
      replaceStep:true,
      idField:3
    },
    {
      textStep:'yb=y-b',
      orderStep:4,
      evaluateStep:true,
      notShowStep:true,
      idField:3
    },
    {
      textStep:'x=yb/a',
      orderStep:5,
      replaceStep:true,
      idField:3
    },
    {
      textStep:'x=yb/a',
      orderStep:6,
      evaluateStep:true,
      idField:3
    },
    {
      textStep:'y=a*x+b',
      orderStep:1,
      idField:4
    },
    {
      textStep:'b=y-a*x',
      orderStep:2,
      idField:4
    },
    {
      textStep:'b=y-a*x',
      orderStep:3,
      replaceStep:true,
      idField:4
    },
    {
      textStep:'ax=a*x',
      orderStep:4,
      evaluateStep:true,
      notShowStep:true,
      idField:4
    },
    {
      textStep:'b=y-ax',
      orderStep:5,
      replaceStep:true,
      idField:4
    },
    {
      textStep:'b=y-ax',
      orderStep:6,
      evaluateStep:true,
      idField:4
    },
    {
      textStep:'x=(-b +- sqrt(b^2-4*a*c))/(2*a)',
      orderStep:1,
      idField:5
    },
    {
      textStep:'x=(-b +- sqrt(d))/(2*a)',
      orderStep:2,
      replaceStep:true,
      idField:5
    },
    {
      textStep:'d = b^2-4*a*c',
      orderStep:3,
      idField:5
    },
    {
      textStep:'d = b^2-4*a*c',
      orderStep:4,
      replaceStep:true,
      idField:5
    },
    {
      textStep:'ac4 = 4*a*c',
      orderStep:5,
      evaluateStep:true,
      notShowStep:true,
      idField:5
    },
    {
      textStep:'b2 = b^2',
      orderStep:6,
      evaluateStep:true,
      notShowStep:true,
      idField:5
    },
    {
      textStep:'b24ac = b2-ac4',
      orderStep:7,
      evaluateStep:true,
      notShowStep:true,
      idField:5
    },
    {
      textStep:'d = b2-ac4',
      orderStep:8,
      replaceStep:true,
      idField:5
    },
    {
      textStep:'d = b24ac',
      orderStep:9,
      replaceStep:true,
      idField:5
    },
    {
      textStep:'d = b24ac',
      orderStep:10,
      evaluateStep:true,
      notShowStep:true,
      idField:5
    },
    {
      textStep:'x=(-b +- sqrt(d))/2*a',
      orderStep:11,
      replaceStep:true,
      idField:5
    },
    {
      textStep:'a2=2*a',
      orderStep:12,
      evaluateStep:true,
      notShowStep:true,
      idField:5
    },
    {
      textStep:'root=sqrt(d)',
      orderStep:13,
      evaluateStep:true,
      notShowStep:true,
      idField:5
    },
    {
      textStep:'x=(-b +- root)/a2',
      orderStep:14,
      replaceStep:true,
      idField:5
    },
    {
      textStep:'x1=(-b + root)/a2',
      orderStep:15,
      replaceStep:true,
      idField:5
    },
    {
      textStep:'x1=(-b + root)/a2',
      orderStep:16,
      evaluateStep:true,
      idField:5
    },
    {
      textStep:'x2=(-b - root)/a2',
      orderStep:17,
      replaceStep:true,
      idField:5
    },
    {
      textStep:'x2=(-b - root)/a2',
      orderStep:18,
      evaluateStep:true,
      idField:5
    }
  ]);
}
